language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pydash

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5

# safelist
branches:
  only:
  - master
