language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5

# safelist
branches:
  only:
  - master
